### ISSUE TITLE
will_close is not fired for subviews

### ISSUE THREAD

**Issue by controversial** [omz/Pythonista-Issues#107]
``` python
>>> class MyView(ui.View):
...     def will_close(self):
...         print("Closing!")
...         
>>> a = MyView()
>>> a.present(); a.close()
Closing!
>>> b = ui.View()
>>> b.add_subview(a)
>>> b.present(); b.close()
>>> # Nothing!
```

**Comment by dgelessus** [comment]
I'm not sure if this is a bug. `will_close` implies that it's only called when the view itself is closed (using the title bar button, swipe gesture or the `close` method). Though maybe there should be a different method/callback that is called when the view is no longer visible, kind of like `wait_modal` in a background thread.

**Comment by controversial** [comment]
Hmm... maybe. There should definitely be more callbacks on ui.View objects.

Can you think of any disadvantages to firing `will_close` on subviews,
though?

**Comment by lukaskollmer** [comment]
`UIKit` has a `viewWillDisappear` method on `UIViewController`s that's
called every time the view is about to e dismissed. There's no such method
on `UIView` but since `ui.View` seems to be some combination between the
two @omz surely could add these methods to `ui.View`.

On `UIViewController`, there's also `viewWillAppear`, `viewDidAppear` and
`viewWillDisappear`

--
Lukas Kollmer
lukas@kollmer.me

**Comment by zrzka** [comment]
I don't think it's a good idea to add `will_close` to all subviews. It's "unfortunate" that there's just `ui.View` and the complexity behind it (`UIViewController`, `UIView`, ...) is hidden. This leads to issues like this one. But I understand that it was done to make the things simpler.

Anyway, I removed `bug` label, because it behaves correctly and it's documented:

```
    def will_close(self):
        # This will be called when a -> presented <- view is about to be dismissed.
        # You might want to save data here.
        pass
```

**Comment by zrzka** [comment]
Closing, doesn't make much sense.
