### ISSUE TITLE
ui.Rect

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#115]
Hmmm... Omz you have done so much to enhance the ui elements especially the addition of dynamic attrs. 
This can't be done in the same way with ui.Rect as far as I can see. I mean adding dynamic attrs to a ui.Rect. I understand there could be a very good reason for this. But if possible, it would be great if you could add a tag property to ui.Rect. I can see this could possibly also break things, I am not sure. But would be so handy to have. I still have some hope, because I now see they often use tags in the iOS classes . Lol, old HyperCard programmers for sure 😁

Also would be great if ui.Rect appeared in the help files under the ui section, as well as if the autocomplete knew about ui.Rect. Currently the editor only recognises scene.Rect. I think there are more like ui.Rect lurking around also

**Comment by Phuket2** [comment]
Ok, unless I wrong, which is the norm. It looks to me that ui.Rect is not from the iOS foundation classes. From what I can see its your creation as a helper built around CGRect and other simlar helper functions.

**Comment by omz** [comment]
> From what I can see its your creation as a helper built around CGRect and other simlar helper functions.

@Phuket2 Yes, that's correct.

One of the reasons that `ui.Rect` doesn't support subclassing or custom attributes is that it would require more boilerplate code because memory management gets a bit more complicated with those capabilities (for example, the way it is now, the class can ignore the cyclic garbage collector completely). I could also make the argument that it has an impact on performance and memory consumption, but actually I don't think it would be that big of a deal.

However, that's not the only reason – given the way `ui` works internally, I think that adding custom attributes to `ui.Rect` (and `ui.Point`, `ui.Size`...) could lead to unexpected behavior, and perhaps be less useful than you think. Basically, all the `ui` elements that use rects do _not_ store an actual `ui.Rect` object internally. The rect is simply converted to a `CGRect`, and passed on to the underlying UIKit object. When you read a rect-like attribute, a new object is constructed from the `CGRect`, so anything you'd add to it would basically get lost in the conversion process.

Btw, the conversion to `CGRect` works for any 4-number sequence, e.g. a `tuple`, `list`, or whatever, so that it's possible to do something like `view.frame = (0, 0, 100, 100)` instead of `view.frame = ui.Rect(0, 0, 100, 100)`, but still getting a proper `ui.Rect` object back when you access the attribute later (you probably knew that).

While it wouldn't be _that_ hard to support custom attributes etc. for `ui.Rect`, making this actually useful would require pretty substantial changes that I don't really think are worth it.

**Comment by Phuket2** [comment]
Omz, I sort of understand what you say. What if you just had a name property. Would that still create the same issues for you? Because even a str name property/attr would be so useful. So unlike a tag attr, you can't store anything in there. Is only a string vrs a object etc

**Comment by Phuket2** [comment]
Omz, should I just close this issue?

**Comment by zrzka** [comment]
Agree that it's not worth it and even OP asked if issue should be closed, closing.
