### ISSUE TITLE
Evernote is not yet Python 3 compatible

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#117]
http://omz-software.com/pythonista/docs/ios/evernote.html contains print statements without parentheses.  Even when fixed, it does not run in Python 3.

**Comment by cclauss** [comment]
https://pypi.python.org/pypi/evernote makes it clear that the current `evernote` API is Python 2 with a Python 3 version still in Beta.

**Comment by jsbain** [comment]
can we change the title here to "evernote is not py3 compatible")?  seems like this should be a pull request over to the evernote api folks, not pythonista....

**Comment by jsbain** [comment]
workaround: install
https://github.com/evernote/evernote-sdk-python3 
in site-packages3/evernote

**Comment by mikaelho** [comment]
Tried this workaround, complains about cStringIO in thrift import. Given the year that has passed since last comment on this issue, has there been anything new about Evernote SDK in Pythonista?

**Comment by mikaelho** [comment]
Workaround was successful after copying also the thrift package from Python 3 SDK lib directory to site-packages.

**Comment by zrzka** [comment]
Removing `bug` label, `evernote` did not release Python 3 support in their package yet. There's https://github.com/evernote/evernote-sdk-python3 as @jsbain pointed out, but it has no sense to include it in the Pythonista, because README says:

> This is a test SDK! The official Evernote SDK for Python doesn't support Python 3 yet; this repository is an experiment as we try to migrate.

Guess, time to wait. Keeping it open, so, it can be checked from time to time if `evernote` package already supports Python 3.

**Comment by mikaelho** [comment]
Probably a longer wait still for a version that would be compatible with aiohttp.
