### ISSUE TITLE
Sticky exception when thrown from inside controller_changed

### ISSUE THREAD

**Issue by robnee** [omz/Pythonista-Issues#144]
I have a problem with Pythonista where, if I have a bug in my Scene.controller_changed function that throws an exception even after the bug is fixed the old exception will still be thrown every time controller_changed is called. This can be reset by force-quitting Pythonista. It's annoying because it makes you think your bug fixes aren't working.

1) Run code below.
2) Notice that both a sceen touch and controller input thows an exception.  You must do this to demonstrate the problem.
3) Fix bug in touch_began by quoting the word 'bug'
4) Confirm that the exception on screen touches disappears
5) Fix bug in controller changed in the same way
6) Notice that the exception DOES NOT go away even though the code has been changed.

```
'''\
This program tries to demonstrate a problem in Pythonista where an exception thrown inside
controller_changed becomes "sticky" and will be rethrown even after the problem code is fixed.
'''
import scene


class MyScene (scene.Scene):
    def touch_began(self, touch):
        # This bug can be fixed after an exception is thrown as one would expect
        print(bug)
    
    def controller_changed(self, id, key, value):
        if key == 'button_x' and value:
            # This bug, once it triggers an exception, cannot simply be fixed.  One must
            # restart Pythonista to reset the interpreter.
            print(bug)


if __name__ == '__main__':
    scene.run(MyScene())
```

**Comment by omz** [comment]
The reason for this is basically that throwing an exception can have the effect of keeping a `Scene` object in memory because the debugger, `sys.last_traceback` etc. are still holding references to it.

As you've seen, this can become a problem because scenes receive controller events regardless of whether they're currently on screen or not. The idea is that this makes it possible to handle game controller events without necessarily rendering anything (e.g. if you want to use game controllers in a `ui` or commandline-based script for some reason).

As a workaround, you could always check first if the scene is actually on screen in your `controller_changed` method, e.g. like this:

```python
class MyScene (scene.Scene):
    def controller_changed(self, ctrl_id, key, value):
        if not self.view:
            # Not on screen, ignore any controller events
            return
        # do other stuff...
```

**Comment by robnee** [comment]
Got it.  Thanks for the explanation!  Is there any way to reset the environment short of a force-quit?

**Comment by omz** [comment]
@robnee Not really. A lot of things (e.g. global variables, imported modules) are reset automatically each time you run a script, but certain things are basically impossible to fully reset without restarting the app.
