### ISSUE TITLE
ui.ListDataSource - Delegate not being called correctly

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#162]
At least when you subclass ui.ListDataSource and do ui.TableView.delegate = subclassed_obj, the methods definded in the class aren't called.  
Forum reference - https://forum.omz-software.com/topic/3468/subclassing-ui-listdatasource-dealing-with-events

**Comment by jsbain** [comment]
The description is not accurate... this should atate that when adding an `action` method to a subclasses ListDataSource, the `action` attribute gets set to None during the constructor.

I don't think this is a bug, instead an enhancement.  The enhancement is to have ListDataSource init check if action is define before setting it to None.

But, not a bug, because there is really no reason to expect that if you reuse attribute names in a different way than the parent class, that it will work as expected.  For instance, suppose action was a @property, which gets nuked when overriding in the subclass.

A work around for Phuket2 would be to use a differnt name, and set self.action=selr._action inside init, or else, store the original:
 
    def __init__(self, *args, **kwargs):
        action=self.action
        ui.ListDataSource.__init__(self,*args, **kwargs)
        self.action=action
