### ISSUE TITLE
hidden attr of ui.View appears not to be handled by kwargs

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#178]
I have no idea if this is a new or old problem. But if hidden=T/F attr is passed in kwargs, it's not being honored.  Surprising as I thought all kwargs were handled for ui.Views/subclasses

**Comment by jsbain** [comment]
The docs are pretty explicit about which attributes can be set with kwargs, and it is a small list:

> class ui.View([frame=(0, 0, 100, 100), flex='', background_color=None, name=None])

I think there is a suggestion somewhere else already that all attributes should be settable as kwargs, since it would facilitate creation of views with less code (a common example are ui.buttons or ui.Labels)
