### ISSUE TITLE
etiquette Here for closing items? 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#192]
I think that unless someone points out to me that what I reported is wrong, I should not close an item even if it's been fixed by @omz .  I assume it's up to him to decide when items are closed unless you decide yourself you were foolish or someone points it out to you.

This is a pretty nice system here (we'll sort of) , but even I can see , going from open to closed is a little dramatic. They could have 5 steps in between, but at the absolute minimum you think they would have like a 'for review' step.  In that stage maybe you just vote, was fixed, or not with a comment.  

But please tell me if I have it wrong about the responsibility of who closes items. I am just trying to do it correctly.

**Comment by cclauss** [comment]
My basic principle would be that we should try to minimize the mundane work that @omz needs to do so that he can focus his attention on the miraculous work of building the product.  If someone else in the community can complete a task then they should do so instead of leaving it for @omz  to do.

Certain issues like https://github.com/omz/Pythonista-Issues/issues/184 are easy for the original submitter to test and close.  We want his attention focused on issues that are still unresolved and on adding new features.

**Comment by Phuket2** [comment]
@cclauss, I agree.  I have no problem with what you say.  It's just if @omz using this a a working todo list, it might be annoying for him if we are going in closing items.

**Comment by omz** [comment]
Feel free to close issues that are fixed, especially if you opened them yourself. It's easy to re-open them if it turns out that the fix was incomplete or something like that, and I don't really use this as a working todo list (one issue here may be multiple smaller items on my todo list).

**Comment by controversial** [comment]
Just labeled everything for you, @omz ;)

2 pages of people's grievances to work through still, but at least it's categorized now. Keep up the great work, the new betas look awesome.
