### ISSUE TITLE
Callback on ui.View Name press

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#218]
It appears that the ui Module is doing some gymnastics if a view is presented with a webview as a subview in full_screen or panel mode.  The gymnastics is that if you click the menu bar it sets the vertical scroll component to zero. As you would Expect, well in most circumstances.  Auctually, I just found out it does work for popover and sheet also.  However you have to hit the screens menu bar not the views menu bar.  Well happy that works, as I say just found out.  

However, it seems to me that this feature/function should try to be not so smart.  Maybe by default it could be. But let's say in a custom ui.View you had a callback like title_clicked, then you could respond to the event yourself.  And in popovers and sheets, the event would result from a touch event on the titles label **not** the main menu bar.  

Below is just what I used to test

``` python
import ui

class MyClass(ui.View):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.make_view()

    def make_view(self):
        wv = ui.WebView(frame=self.bounds)
        wv.flex = 'wh'
        wv.load_url('https://www.google.com.au/search?client=safari&hl=en-au&q=google+us+election&spell=1&sa=X&ved=0ahUKEwig1dWpo-fPAhWLo48KHb83A1QQvwUIFSgA&biw=1024&bih=1247')
        self.add_subview(wv)

if __name__ == '__main__':
    _use_theme = True
    w, h = 600, 800
    f = (0, 0, w, h)
    style = 'panel'

    mc = MyClass(frame=f, bg_color='white', name='Test WebView')
    mc.present(style=style, animated=False)
```

**Comment by zrzka** [comment]
This is iOS feature called scrolls to top and it has nothing to do with title in the navigation bar. It works when you tap on status bar (carrier, time, battery, ...). `UIScrollView` offers [scrollsToTop](https://developer.apple.com/documentation/uikit/uiscrollview/1619421-scrollstotop?language=objc) property where you can control if this feature is enabled / disabled for your view. It can probably be added, but not sure about this, because it will be more messy in a current situation we have now - `ui.View` combines `UIView`, `UIViewController` and it's starting to be a _mess_. Closing this one and will fill new issue about `scrollsToTop` property.
