### ISSUE TITLE
When clearing search bar in library, letters remain highlighted in folder names

### ISSUE THREAD

**Issue by omz** [omz/Pythonista-Issues#22]
The highlighting of matches in folder names isn't cleared completely when the search bar becomes empty.

**Comment by dgelessus** [comment]
Pythonista 3.1 (build 301016, App Store version), iPhone SE, iOS 10.2.

Mostly fixed, but this still happens when the names of the special "Pythonista 2 Documents" or "Modules & Templates" folders match the search. In that case, clearing the search bar removes the highlights on all folders except these two. Moving them out and back into view removes the stuck highlights.

**Comment by zrzka** [comment]
@dgelessus can you please try it again? Trying to reproduce it in 311014 and I'm unable to reproduce it / doing it in a wrong way. Asking, because similar issue of mine (#323) no longer happens to me.

**Comment by dgelessus** [comment]
No, doesn't happen anymore. All "special folders" have been moved to the top level now, and top-level things don't appear in the search.
