### ISSUE TITLE
Question about ver 301012 comments - re implementing draw func

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#234]
@omz you mention this will me more light weight now for custom ui.Views and it has knock on effects for widgets, if you don't override the draw method/func.  
So is this a bug that has been fixed? I mean, have custom ui classes  , been acting as if the draw method had been overridden regardless if it had or not.  Meaning all the bufferers/double screen buffering been allocated regardless? Not trying to be smart, just trying to get it.

**Comment by omz** [comment]
It's not really a bug that's been fixed, more of an optimization. As far as I know (this isn't very well documented by Apple), `UIView` creates a pixel buffer for drawing if the view implements a `drawRect:` method (the equivalent of `ui.View.draw` in Pythonista), even if the implementation is empty, so it's generally advised (e.g. in Apple sample code) not to implement it at all, if it isn't actually used.

Up until now, the underlying `UIView` class that is wrapped by `ui.View` always implemented `drawRect:`, even if the `ui.View` class didn't actually need it, because it was a bit easier to implement that way (no need to check what the `ui.View` class actually implements). If `draw` wasn't implemented by the Python class, this had the same effect as an empty `drawRect:` implementation in the `UIView` subclass – causing no visible difference, but potentially more memory being used.

**Comment by Phuket2** [comment]
Ok, thanks for the explanation.  The Pythonista docs talk about only overriding the draw method in ui custom classes if you need to, because of resource usage. I thought i understood why, Memory allocation for double buffering etc, which makes sense ...that was the only reason for my question.  
So it seems like there was a side effect you could not control until now.  Again. I am not trying to be smart, just trying to understand
