### ISSUE TITLE
Missing readline module support

### ISSUE THREAD

**Issue by esanker** [omz/Pythonista-Issues#242]
I tried installing from the Python Package Index using StaSH's pip (ex. gnureadline, pyreadline, pyreadline-ais) but it broke the some of Pythonista's builtin modules like flask.

**Comment by jsbain** [comment]
Since this is not a open source platform, readline cannot be installed.  
if tou are asking how to fix what you broke, go to site-packages, delete all of the folders that were installed when you installed readline, then force quit pythonista.  You can always get back to "stock" pythonista by simply deleting the site-packages folder.

**Comment by esanker** [comment]
OK.  Thanks for the tip ;-)
