### ISSUE TITLE
Custom file extensions for plain text files

### ISSUE THREAD

**Issue by omz** [omz/Pythonista-Issues#26]
When creating a new file with the "Plain Text" template, and entering a name that includes an extension (like `.csv` for example), that extension should probably be preserved instead of replacing it with `.txt`.

**Comment by averville** [comment]
It looks like this simple enhancement is not high in priorities. I have this problem when creating parameters files and find it annoying having to correct the extension afterwards after having entered it correctly when creating a file. Please just check if any "point" has been entered when a file name is given, then apply the text that goes afterwards as the right extension instead of .txt

**Comment by zrzka** [comment]
Extension is preserved in the 311014 (when created as Plain Text).
