### ISSUE TITLE
numpy.ndarray.dump() throws _pickle.PicklingError

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#260]
```python
import numpy
with open('a_zero.pkl', 'wb') as out_file:
    numpy.zeros(1).dump(out_file)
```

```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/C2DC6C38-3D98-4394-B761-B6CA01482067/Pythonista3/Documents/from GitHub/deep-learning-from-scratch-master/dataset/numpy_dump_test.py", line 3, in <module>
    numpy.zeros(1).dump(out_file)
_pickle.PicklingError: Can't pickle <built-in function _reconstruct>: import of module 'multiarray' failed
```

* https://github.com/cmusatyalab/openface/issues/30
* http://askubuntu.com/questions/230907/import-numpy-no-module-named-multiarray

**Comment by Deviper-Labs** [comment]
I know this bug is kind of old, but I'd done some testing after getting the same error and found a workaround to this.

From what I'd found, it seems the multiarray module that fails to be imported DOES actually exist but the interpreter (in 3.6) can't import it. I tested it with Python 2 in Pythonista and it somehow works. So it seems that the Python 2 one works, but the 3.6 doesn't.

Don't know how this is gonna be fixed, but in the mean time, this is the workaround:

Just copy the multiarray.py file from `Python Modules/Standard Library (3.6)/site-packages/numpycore/multiarray.py` to `Python Modules/site-packages-3` instead, so that it uses that instead of failing.

OR

Create a new script in `Python Modules/site-packages-3` called `multiarray.py` and add the following.

```python
from _np_multiarray import *
from _np_multiarray import _ARRAY_API, _fastCopyAndTranspose, _flagdict, _get_ndarray_c_version, _reconstruct, _vec_string
```
