### ISSUE TITLE
No LZMA support

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#268]
Why isn't there LZMA support?

**Comment by omz** [comment]
https://forum.omz-software.com/topic/3853/support-lzma/4

**Comment by scj643** [comment]
Ah any way for someone on a jailbroken device to add it?

**Comment by scj643** [comment]
What if you renamed the liblzma and refactored it then would it link to Apple's private version?

**Comment by chibill** [comment]
Can't you appeal to Apple saying your packaging lzma?

**Comment by scj643** [comment]
Would be the same case for lxml too

**Comment by jsbain** [comment]
Turns out that LZMADecompressor i linked to was mostly written by @pudquick, who did a lot of puthonista innovation back in the day.  Anyway, his original works perfectly for me in pythonista.  I commented out line 85 for use in pythonista 3.x.  https://gist.github.com/pudquick/50c5510785ec29de8f36
Replace line 53 `lzma_alone_decoder` to `lzma_stream_decoder` to decode xz files.

**Comment by controversial** [comment]
Seems like there's a good reason for this module's exclusion and also a good workaround.

**Comment by pudquick** [comment]
@jsbain - I do have specific code for xz decompress, FYI: https://gist.github.com/pudquick/9f9023f8e9b1a9af53d0

All of this was written for macOS. If it works for you for Pythonista as well, I'm happy to hear it 😄

**Comment by scj643** [comment]
lzma is a python built in not an external module.
