### ISSUE TITLE
Tags for icons when searching

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#275]
I tend to always finding myself looking for an icon matching a tag. Having the icon chooser item's have tags that are related to what they represent.

**Comment by controversial** [comment]
This would be a lot of work to implement since it's likely that not all icons have tags available beyond their names. I believe ionicons have some kind of basic tag repository associated with them since it's possible to search on the [ionicons docs](https://ionicframework.com/docs/ionicons/) for words beyond the icon name (ex. searching for "plus" yields the "add" icon). However, I don't know where this repository of alternate names is stored, and it's unlikely that all of Pythonista's included icon sets would have this available.

**Comment by zrzka** [comment]
Closing this one, some of these sets have tags, some of them not, ... Then another kind of issues will arrive like - add tags to this set, because ionicons have them, ...
