### ISSUE TITLE
photos: AssetCollection.subtype returns AssetCollection.type

### ISSUE THREAD

**Issue by Dutcho** [omz/Pythonista-Issues#295]
Current beta v3.1.1 (311004) returns an unexpected subtype:
```
>>> import photos; photos. photos.get_favorites_album().subtype
'smart_album'
```
[Documentation](http://omz-software.com/pythonista/docs/ios/photos.html) specifies ``` 'favorites'``` as to be expected result. May well be caused by a typo in function logic, but as it's built-in I cannot verify this theory

**Comment by omz** [comment]
You're right, thanks! This is indeed a typo (the `subtype` and `type` attributes point to the same getter). Should be fixed in the next beta.

If you need a workaround right now, you can use `objc_util` to get the actual subtype:

```
from objc_util import ObjCInstance
import photos

favs = photos.get_favorites_album()
subtype = ObjCInstance(favs).assetCollectionSubtype()
```

NOTE: subtype will be an integer, possible values are listed in Apple's [PHAssetCollectionSubtype documentation](https://developer.apple.com/reference/photos/phassetcollectionsubtype?language=objc). You'll see the actual integer value when you click on one of the enum names, e.g. favorites => 203.

**Comment by Dutcho** [comment]
Thanks for the workaround!
The most recent beta v3.1.1 (311008) changed getter `subtype`'s behaviour: it now returns `None` (instead of the same result as `type` as it did previously); still not terribly useful, but hey, I've got the workaround, so not to worry (and it's great to have Python 3.6 with the f-strings)

**Comment by omz** [comment]
Thanks, I'll look into it again.

**Comment by zrzka** [comment]
Fixed in 311015.
