### ISSUE TITLE
Deleting highlighted text with delete key does not always work

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#301]
Beta 311008, if some text is highlighted and you hit the delete key, does not always delete the text.  
On Ipad pro 12.5' using coding keyboard , with iPad Pro + Special characters layout.  I have swapped out different settings, but have not managed to see a reliable pattern when it fails.

**Comment by omz** [comment]
Chris has mentioned this as well, but there doesn't seem to be a clear pattern.

I haven't seen this behavior myself, but I currently think that it's probably irrelevant because I plan to remove the coding keyboard from one of the next builds anyway.

The new keyboard on iOS 11 makes it largely superfluous, and having to maintain feature parity with the system keyboard might become a maintenance burden in the future.

**Comment by cclauss** [comment]
The pattern is that the selected text needs to start on a line that is indented.

```python
def do_not_select_this_line():
    but_instead_select_this_line = True
```

**Comment by zrzka** [comment]
Seems this one is obsolete and can be closed @omz?
