### ISSUE TITLE
Behavior of the extended keyboard numbers is buggy for splitview on iPad (disappears)

### ISSUE THREAD

**Issue by dcookdesign** [omz/Pythonista-Issues#35]
(But hopefully the entire extended keyboard can just always be hidden when there is a BT keyboard active)

**Comment by jsbain** [comment]
What is "Inconsisten"t?  screenshot or more explanation?

**Comment by danrcook** [comment]
Sorry... This same behavior exists when using a Bluetooth keyboard and not. I think it's more pertinent when not using a Bluetooth keyboard because of course you'd want to use the number row (if you have it on). Maybe need to rename this issue. I'll try to do that.

Here are some pictures. I've number the sequence of events 1-5. It does the same with either Bluetooth keyboard or onscreen keyboard.

The big bug part about this is that once the number row has disappeared it seems to get it back you have to switch to another file or perhaps shut down Pythonista and restart.

![image](https://cloud.githubusercontent.com/assets/12954427/16301499/a723933c-3980-11e6-81d6-ec0e7e3ac1d3.jpeg)

**Comment by zrzka** [comment]
Row with numbers is gone. If it will be added back, we can retest, reopen or file a new issue.
