### ISSUE TITLE
The "Python" section in the top-level file list...

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#422]
...seems a bit odd IMHO. The heading is not really accurate, "Modules & Templates" contains more than just the Python stdlib, and "Pythonista 2 Files" doesn't really fit there either. The "Pythonista 2 Files" section seems like it would fit better under "External Files", and the "Modules & Templates" could be moved to the bottom of the "Script Library" section (since the site-packages and templates are "user folders" too).

**Comment by omz** [comment]
Yeah, I'm not completely happy with this either. Moving "Pythonista 2 Files" to "External Files" makes a lot of sense, hadn't thought of that.

I agree that moving "Modules & Templates" to the "Script Library" section would make sense "semantically", but I kinda don't want to make the placement too prominent because I think that *most* people will rarely need it...

**Comment by omz** [comment]
I've removed the section header entirely for the "miscellaneous" section at the bottom (build 311016). Kind of a kitchen sink now, but I think it's okay.
