### ISSUE TITLE
The syntax pop up window loses its expand control if its minimised

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#425]
Beta 311013, seems you have to do a hard restart to see the expander control again. Sorry I could not get the Dropbox pic to load inline. Not sure its me or a bug with Dropbox or ios11.03

https://www.dropbox.com/s/9r65lc93925pnk0/File%2018-10-17%2C%2019%2052%2051.jpeg?dl=1

**Comment by dgelessus** [comment]
@Phuket2 This seems to work: `![text](https://dl.dropbox.com/s/9r65lc93925pnk0/File%2018-10-17%2C%2019%2052%2051.jpeg?dl=1)`

![text](https://dl.dropbox.com/s/9r65lc93925pnk0/File%2018-10-17%2C%2019%2052%2051.jpeg?dl=1)

(had to replace `www` with `dl` in the Dropbox link)

Alternatively you can also upload images directly to GitHub. Under the comment text box there is a line of text explaining how to do that. On iOS you can tap on the "selecting them" link, since drag/drop and copy/paste do not work (I think).

**Comment by omz** [comment]
This should be fixed in the new beta (build 311014).

**Comment by Phuket2** [comment]
Confirmed, fixed :)
