### ISSUE TITLE
Force a script to stop

### ISSUE THREAD

**Issue by controversial** [omz/Pythonista-Issues#45]
Could we have a way to forcibly terminate a script, even if it's catching `KeyboardInterrupt` exceptions? I've encountered scripts in the wild that are almost impossible to stop from Pythonista.

This could, perhaps, be activated via a long press on the `[x]` button.

**Comment by omz** [comment]
While it would certainly be useful in some situations, I cannot think of a way this could actually be implemented. Since all scripts run in the same process as the app itself, there isn't really a way to "kill" a script.

**Comment by controversial** [comment]
Ok, thanks.

**Comment by mikaelho** [comment]
Is there a middle ground, where a long press could send a signal instead of killing the process outright? One concrete use case for this would be compatibility with libraries that depend on getting a signal instead of KeyboardInterrupt; see e.g. [trio issue #684](https://github.com/python-trio/trio/issues/684).
