### ISSUE TITLE
Opening help for 2nd time should open Overview page

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#453]
If I open the help system the first time with ‚?‘, I get the overview page.
If I open another help page and close this tab and press ‚?‘ again, I get this last opened page. I expect to get the overview page.

**Comment by zrzka** [comment]
I consider this as a bug, I would expect overview page as well. User can keep help open if he wants to stay on the same page.

**Comment by cclauss** [comment]
This title of this issue could be improved to be more self explanatory.  Is this a “nice to have” low priority issue?

**Comment by zrzka** [comment]
From my POV, nice to have. Issues will be sorted by priority in the 2nd round.

**Comment by dgelessus** [comment]
FWIW, this behavior comes from old versions of Pythonista that didn't have tabs in the console. In those versions, the documentation would show as a full-screen popover view instead. In that situation you wouldn't want the location to be reset every time you reopen the view, because then you couldn't easily switch back and forth between editor/console and docs. Of course this doesn't apply anymore now that we have tabs.

IMHO, the best solution to this would be to allow multiple documentation tabs (like in Editorial). Then the behavior of the documentation button is naturally "open new tab with the home page".

**Comment by zrzka** [comment]
Bug -> enhancement, like what @dgelessus suggested.

**Comment by omz** [comment]
Shouldn't be an issue anymore in build 31106, I've implemented multiple documentation tabs, as suggested by @dgelessus.

**Comment by wnMark** [comment]
Thank you Ole
