### ISSUE TITLE
The trash is missing

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#457]
Obviously you're aware of this, but I wanted to have it listed here. The trash is a useful safety feature so that you won't lose anything if you tap the wrong button in the swipe menu. Of course backups and version control exist, but it's always good to have an extra layer of protection against accidental data loss.

I'm guessing part of the reason why the trash is currently missing is that it might be more difficult to implement well for the iCloud folder, and because iOS 11's Files apparently has a built-in trash? My devices are still on iOS 9/10 and many of my Pythonista files are not in iCloud yet, so I would find a Pythonista-internal trash very useful (even if it only works for local files).

**Comment by zrzka** [comment]
You can't tap on a wrong button, because there's just delete button. See attached screenshots. Open in new tab and favorite buttons are on the other side.

I assume that the trash was removed intentionally. @omz planning to add it back or close as won't fix? I'm perfectly happy without Trash, never used it, even once.

![4b26be42-1be0-4857-93fb-10357b707e4e](https://user-images.githubusercontent.com/1084172/32123324-055d42b6-bb64-11e7-9943-ed22869941d7.jpeg)

![8113062c-98f9-41f1-b90c-3e2d4378fd21](https://user-images.githubusercontent.com/1084172/32123296-edc89c7c-bb63-11e7-978d-8686e7c25a2a.jpeg)

**Comment by dgelessus** [comment]
As usual, on iOS 11 everything looks completely different. :) On iOS 9/10, there is no "swipe to right" menu, and the "swipe to left" menu contains "Delete", "+ Fav", "+ Tab".

That's not the point though, tapping the wrong button was just an example. I might also realize after tapping the Delete button that I had the wrong file selected.

**Comment by zrzka** [comment]
Aargh, okay, your comment forced me to install Pythonista on the 1st iPad with iOS 9 :))

**Comment by omz** [comment]
The trash feature is back in build 311016.
