### ISSUE TITLE
Multiple issues for a repo - idea

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#489]
It seems like github can do many things.  I wonder if its possible to have multiple issue lists.  But I think it would be great to have a feedback list that didn't interfere with the bug/enhancement issue list.  So we could comment on what really works well.  
Eg. I love the folder icon that now appears in the source dropdown list so you can see the file in the file system. It's a small thing, but its so great.  But reporting bugs etc is very important, but Ithink its just as important to be able to report what really works well

**Comment by cclauss** [comment]
Could you the desired separation via GitHub labels?

**Comment by zrzka** [comment]
If something works well, use the forum and write about it. Issues are all about bugs, enhancements, ... (actual work to do), but not appraisal. Or you can write to Ole directly.

Closing this one as it is not an issue. Trying to keep this list short. It doesn't belong here. If you'd like to discuss it, you can start a topic in the forum.

**Comment by Phuket2** [comment]
@zrzka, I understand.  But I always feel uncomfortable talking about beta items on the forum.  I do it, but I always feel funny when I do.  I feel like it puts extra pressure on @ole as well as confusing ppl who dont have access to the beta.  My idea was not about giving @omz an ego boost or a pat on the back.  But just to be able to let him know about the things that really work in the right forum So to speak. The example I gave about the folder icon, for me is so fantastic.  Maybe a lot of others have the same feeling.  I feel that sort of feed back can help @omz better understand the effort to real world functionality that certain features produce.  I also agree it should not be in here (the issues) area.  That's why I dont post about such things. But really, I dont have anywhere to post about them.  
Anyway, I will just leave it alone for now.  Just wanted to explain my rationale

**Comment by zrzka** [comment]
@Phuket2 don't feel uncomfortable, it's perfectly okay IMO. What else do you have at your disposal? Forum, issues and email. Email is just 1:1. Issues are bugs, enhancements, ideas, ... Forum is for the rest. You can always use something like `[beta]` in the topic title for example. And if people don't get it, still confused, there's nothing you can do about it. The last thing you do want is some kind of closed beta group (forum, ...) to save people from confusion.

The worst thing you can do is:

> That's why I dont post about such things. But really, I dont have anywhere to post about them.

Use the forum, even for beta related stuff, that's why it's there and don't worry about it. I mean it.
