### ISSUE TITLE
Fatal read error on socket transport

### ISSUE THREAD

**Issue by yjqiang** [omz/Pythonista-Issues#555]
Fatal read error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1177ce940>
transport: <_SelectorSocketTransport fd=47 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/9F565D30-C54B-4210-902B-874D7A5AB814/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/selector_events.py", line 725, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out

**Comment by cclauss** [comment]
Looks like a normal network reliability issue.  A network read operation has timed out.  Can you get a faster/more reliable network connection?

**Comment by yjqiang** [comment]
But it should not to show that. If it showed it, the program should break down, since "fatal" sounds very bad.

**Comment by yjqiang** [comment]
And I have already set a timeout for 1.5 seconds on each request.

**Comment by cclauss** [comment]
Around this code you can put the following:
```python
try:
     <this code goes here>
except TimeoutError:
    print("Sorry but the network seems to be acting up.  Please try again.
```
Or instead of the print message, you could retry yourself.

**Comment by yjqiang** [comment]
I have already used the "try", but still it shows.

**Comment by cclauss** [comment]
Is you code available on GitHub or similar?

**Comment by yjqiang** [comment]
```py
self.other_session = aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=1.5))


try:
    response = await self.other_session.get(url, headers=headers, data=data)
    if response.status == 200:
        json_response = await response.json(content_type=None)
        if isinstance(json_response, dict) and 'code' in json_response:
            tag = await replay_request(json_response['code'])
            if tag:
                # continue trying this request
                continue
        return json_response
    elif response.status == 403:
        print('403频繁')
except:
   # The network connection is not good
    # print('当前网络不好，正在重试，请反馈开发者!!!!')
    print(sys.exc_info()[0], sys.exc_info()[1], url)
    continue

**Comment by dgelessus** [comment]
The "Fatal read error on socket transport" message comes from `asyncio.selector_events` when it encounters an exception that it doesn't know how to handle: https://github.com/python/cpython/blob/v3.6.1/Lib/asyncio/selector_events.py#L723-L728

I don't know much about `asyncio`, but if it says the exception is fatal, it's probably right. :) A `try` block won't help here, because the exception is logged and not thrown normally. Even if you could catch the exception, the connection would still be broken, so you'd have to restart your script anyway.

It would be useful to know what you're trying to connect to. Is the other end of the connection in your local network, or a server in the internet? If you try to connect to the other end using some other method (for example the `requests` module or a browser), do you get any errors?

A timeout of 1.5 seconds is quite low, if you're on a slow/unreliable network (cellular data) or the other end is slow/overloaded, that could easily trigger the timeout by accident. Try increasing the timeout to something like 10 seconds, or simply remove the setting and use the default timeout.

**Comment by cclauss** [comment]
I do not see the problem.  I will try to look again later today.

I would advise that you [avoid bare exceptions](https://realpython.com/the-most-diabolical-python-antipattern/) and change the except block to something more targeted like:
```python
except TimeoutError as e:
    # The network connection is not good
    # print('当前网络不好，正在重试，请反馈开发者!!!!')
    print(e, url)
```

**Comment by yjqiang** [comment]
@cclauss But there are many different errors, I can't handle it one by one. It is hard. I tried that, but I give up.

**Comment by cclauss** [comment]
@dgelessus is providing better feedback than I can.

**Comment by yjqiang** [comment]
But I think that should not happend, since I use aiohttp to get or post requests, when I find the network connection is bad or it does not return the right answer, it just return the error message or the answer, let me handle the other things. But I can not catch that error, so I think it is a bug.

**Comment by dgelessus** [comment]
I don't know anything about `aiohttp`, but there probably is a way to handle these errors so they aren't shown in the console. You'll need to look into the documentation to find that out.

Also, have you tried the suggestions from my last comment?

**Comment by yjqiang** [comment]
I tried. It does not often show the error mesasges now, but there are some. Thx.

**Comment by yjqiang** [comment]
It is not aiohttp client's bug.
