### ISSUE TITLE
Are we abandoned?

### ISSUE THREAD

**Issue by yjqiang** [omz/Pythonista-Issues#568]
We haven't heard any develop plans for 8 months. Omz did not said anything about Pythonista. We want pandas, we want modules to be updated, we want to try python3.7. We are waiting for the next version. We are still waiting.

**Comment by alexandreleroux** [comment]
A quick search seems to indicate Ole the developer has [not logged on the Pythonista forum since late June 2018](https://forum.omz-software.com/user/omz), while he was otherwise participating regularly. Hopefully there's more recent [activity on his Twitter account, mid-August](https://twitter.com/olemoritz).

I want to dive into Pythonista but I'm eager to learn about its future, especially Python 3 support and the XCode template. At this point I just hope Ole is doing fine and is having fun coding an update to Pythonista we'll all love :-)

**Comment by derekbelrose** [comment]
From October 28th:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I know it‘s been a while since the last update, but I‘m still actively working on Pythonista.</p>&mdash; Ole Zorn (@olemoritz) <a href="https://twitter.com/olemoritz/status/1056501127875887104?ref_src=twsrc%5Etfw">October 28, 2018</a></blockquote>

**Comment by alexandreleroux** [comment]
Thanks @derekbelrose , that's indeed great news. Buying Pythonista right away :-)

@yjqiang , I'd claim this ticket can be closed: we're not abandoned! :-) Cheers

**Comment by yjqiang** [comment]
> Thanks @derekbelrose , that's indeed great news. Buying Pythonista right away :-)
> 
> @yjqiang , I'd claim this ticket can be closed: we're not abandoned! :-) Cheers

But omz said he was working on Editorial on iPhone X several months ago. And now… The latest Editorial was released 1 year ago. 😼

**Comment by yjqiang** [comment]
Anyway, I would like to keep it open until the next release.

**Comment by derekbelrose** [comment]
@yjqiang I didn't mean to defend his absenteeism, all I wanted to state was the @omz was active on Twitter and he said he is still working on it less than 2 weeks ago.

I agree that this should remain open for the duration of the time that we don't see any real activity on the project.

**Comment by yjqiang** [comment]
> @yjqiang I didn't mean to defend his absenteeism, all I wanted to state was the @omz was active on Twitter and he said he is still working on it less than 2 weeks ago.
> 
> I agree that this should remain open for the duration of the time that we don't see any real activity on the project.

No, you are right. Actually I saw this before your comment. But I insist to keep it open. Maybe I just kind of unhappy or what. It's not your fault.

**Comment by cclauss** [comment]
Can we please close this issue and move such discussion to the forum or to Slack.  There are enough open issues already that we do not need chatter about things which are not bugs in software or documentation.

**Comment by yjqiang** [comment]
> Can we please close this issue and move such discussion to the forum or to Slack.  There are enough open issues already that we do not need chatter about things which are not bugs in software or documentation.

Ok. Since it is almost sure that omz is still working on it. I shouldn't insist and confuse others.
