### ISSUE TITLE
Version 320000 :: Console is difficult to open on iPadOS

### ISSUE THREAD

**Issue by sinkaszab** [omz/Pythonista-Issues#617]
When I want to slide my finger from my iPad's right side of the screen towards the center as an iPadOS feature another app will swim in instead of opening the console.

**Comment by dgelessus** [comment]
To open the console you can swipe horizontally anywhere on the screen, it doesn't have to be from the right screen edge. For example if you swipe from somewhere in the right half of the screen (but not at the edge) towards the left, you can access the console without accidentally activating a Slide Over app.

On iOS 12 I never had any issues with activating Slide Over by accident when I wanted the console. I don't know if it's any different with iPadOS 13 (I've only updated very recently). But perhaps it was the same on older iOSes and I simply never noticed it, because I never swipe from the edge to open the console (I always swipe somewhere near the middle of the screen, like I described above).

**Comment by sinkaszab** [comment]
This works, I confirm. Not intuitive or as I got used to it, but works.
