### ISSUE TITLE
argtypes not passed through to objcinstancemethod.__call__

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#68]
sorry if is is not present in latest beta, been in travel so have not yet installed it.

line 801 in obj_util.py
        # Pass through restype and argtypes keyword args:
        kw = {k: kwargs[k] for k in ('restype', 'kwargs') if k in kwargs}
s/b     argtypes instead of kwargs in the tuple of strings.

**Comment by omz** [comment]
No idea what I was thinking there, thanks!

**Comment by jsbain** [comment]
as an aside, is it no longer possible to set .encoding?  I seem to remember in past builds it was possible to override .encoding of an instance, for example there are still several encoding styles that are not correctly interpreted (in this case I was trying to use _pyObject)

**Comment by omz** [comment]
@jsbain It _should_ be possible to set the `encoding` of an `ObjCInstanceMethod`, but you'd need to construct it manually, i.e. using something like `my_method = ObjCInstanceMethod(obj, selector_name)`, instead of accessing an `ObjCInstance`'s attributes.

The reason is that accessing methods via attributes will now produce `ObjCInstanceMethodProxy` objects instead of actual methods. This is because the same attribute can represent multiple different methods (with different encodings). For example, `UIColor.color` can be resolved to both `colorWithRed:green:blue:alpha:` and `colorWithWhite:alpha:`, depending on which keyword arguments you pass to the actual method call...

**Comment by zrzka** [comment]
Check the objc_util.py in 311014, fixed.
