### ISSUE TITLE
Keyboard clicks on iPad don't work completely

### ISSUE THREAD

**Issue by skrohmer** [omz/Pythonista-Issues#74]
When pressing a button of the top row of the iPad virtual keyboard in Pythonista (numbers and operations) I don't get a click feedback. All other keys of the keyboard work fine. iPad 4, iOS 9.3.2, latest Pythonista version.

**Comment by omz** [comment]
Do you have the "Sound Effects" setting turned off?

**Comment by skrohmer** [comment]
No, it's on, and all other keys make "click" ;-), only the top row doesn't.

**Comment by skrohmer** [comment]
Just a small addition: The top row has one more strange behaviour: It reacts quite slowly, I must hit the buttons quite well in the center and I may not be too fast. I cannot use this row with the same speed as I do with all other keys. Maybe it's related to my old and slow iPad. Can anyone reproduce this?

**Comment by omz** [comment]
@skrohmer Are you using iOS 8?

**Comment by skrohmer** [comment]
iPad 4, iOS 9.3.2, latest Pythonista version

**Comment by omz** [comment]
Ah, okay, I overlooked that it's about the numbers row... That's a known issue, and unfortunately not easy to fix because it seems like this is intentional behavior from the system keyboard. It's apparently designed to prevent accidental touches outside of the main keyboard while typing, so there's a certain time interval after pressing a regular key in which touches outside of the main keyboard are ignored.

For the primary row of extra keys, I worked around this by using the "assistant bar" that normally shows QuickType suggestions etc. Unfortunately, it looks like the "touch delay" behavior will extend to this bar as well in iOS 10... A more permanent solution _might_ be to build a completely custom "coding keyboard", instead of extending the system keyboard, but that's obviously a lot of work, and has its own issues... :/

**Comment by skrohmer** [comment]
OK, thanks for the detailed infos. It's better living with this when knowing the reasons for the behaviour ;-). I could also think of an option in the settings to switch off this bar. If you don't see it you won't fall for the slow behaviour. It's quite annoying writing lines like `test = (42 + adams) * 6` when the keyboard lines have to be changed lots of times...

**Comment by omz** [comment]
@skrohmer There *is* an option in the settings to turn off this bar. It's called "Extended Keyboard with Numbers", and I don't even think it's enabled by default.

**Comment by skrohmer** [comment]
Oooops, thanks for opening the eyes ;-). Maybe I have set this at the very first use and forgot it. So for me this is fine now.

**Comment by zrzka** [comment]
Pythonista no longer provides _Extended Keyboard with Numbers_ (or at least I can't find it in the settings). Closing.

**Comment by dgelessus** [comment]
@zrzka The extended keyboard isn't necessarily gone forever. My understanding of the beta release notes is that it's currently unavailable and may be added again later.

**Comment by zrzka** [comment]
@dgelessus yup, now it's gone and _may_ be added again later - then I'm happy to retest and reopen.
