### ISSUE TITLE
Change "Share as Gist" --> "Share as Repo"

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#98]
A repo is an open invitation to community involvement to collaborate on continuous improvement while a gist is merely a dead end.

  As you know from my posts to the forum, I am a big fan of GitHub repos and not a big fan of GitHub gists.  Repos foster collaboration and gists do not.  Often the folks who are using _Share as Gist_ are looking for others to help them with their code.  But others can not create pull requests on a gist and if someone leaves a comment on their gist, the owner is not even alerted to that fact.

  I know that Apple will not allow you to make it easier for users to _pull_ code (read) from repos but writing to a repo should be no more problematic than writing to a gist.  If we could get users over the first hurdle of publishing to repos than I think that many of them would over time learn the complexities of repos (clone, fork, merge, commit, push, pull, pull requests).  When Pythonista start off new users with gists, they will fail to see immediate benefits to GitHub collaboration.  It just feels like PasteBin.

  What I would ask you to consider is replacing _Share as Gist_ with _Share as Repo_.  It would remain a Write Only capability to remain within Apple's guidelines. but at least the owners of these would be notified of comments and could get pull requests.  When the user selects _Share as Repo_, Pythonista could ask if they want to publish just the single file or if they want to publish all files in the current folder.

  I believe that this change would foster more collaboration across the Pythonista community.

**Comment by dgelessus** [comment]
Gists can be posted anonymously though, while repos require a GitHub account. Removing the Gist option entirely would limit this option.

**Comment by filippocld** [comment]
I'd like to have both because sometimes i find gists more useful for my needs

**Comment by cclauss** [comment]
I do understand @dgelessus point about anonymity.

Are there other things that a gist provides that a repo does not?

**Comment by Phuket2** [comment]
cclauss, I agree with you. Would be great to have a publish to a repo. One big step done. But it needs to be able to work on a directory not just a file. I have read before on the forum you can add multiple files to a gist from the share menu, I have never been able to do that. Maybe it's possible. But for a repo, it definitely needs to be the whole folder. Not sure what happens if you publish the same folder twice. You would hope that the files are over written, well that's what I would hope. But if you got an error msg saying the repo already exists, back to square one. Does not really help any one. I am sure the exact right thing should be a merge or something. But without that next step, to update your repo in whatever manner from Pythonista almost makes it worst than a gist for the publisher. I understand it can only be one direction.  But if the publishing was handled in a rock solid way, it may prove easier to make tools to come the other way.
Personally, I would love to see this happen.

**Comment by lukaskollmer** [comment]
What about a "Push to Repo" option that just uploads (adds) a file to a repository?

This would have a few advantages:
- A lot of people have a pythonista-scripts repo where they store a collection of their scripts. (This is great btw because having all scripts as gists would mean they're basically not at all discoverable)
- App Review *should* not have a problem with that, because the "Push to Repository" option would be write-only and no code is downloaded at any point in this process

**Comment by dgelessus** [comment]
@cclauss The [Gist API](https://developer.github.com/v3/gists/) is also much simpler, creating a gist can be done using a simple POST request. [Creating a repo](https://developer.github.com/v3/repos/) and [commiting](https://developer.github.com/v3/git/) is also possible, but requires a bunch of manual work. There's no easy API to create a repo with a bunch of files, or to update multiple files at once. Single files can be updated easily, similar to how the web interface works, but updating multiple files with one commit requires manually creating the blobs and the commit.

**Comment by controversial** [comment]
I'm honestly against this change. A gist can be a quick way to send a file or a few files to someone else if you don't want to make a whole repo. A separate option might be ok. 

@lukaskollmer Conglomeratete Git repos are a bad idea. They clutter diffs and version history. Just make separate repos, and if you must, add them all as submodules to your conglomeration.

**Comment by zrzka** [comment]
@cclauss your issue, I think we can close it? We have iOS 11, drag & drop, file system provider, Working Copy, ... an easy way how to share repos / code. I don't see a reason to include something like this in Pythonista these days.

**Comment by cclauss** [comment]
Please give me 48 hours to try that out before we close this.

**Comment by zrzka** [comment]
I'm not going to close this one, just asked wdyt, if it still makes sense.

**Comment by zrzka** [comment]
@cclauss any news on this one? Asked for 48h 11 days ago :)
